Document: sipwise-asterisk
Title: Debian sipwise-asterisk Manual
Author: <insert document author here>
Abstract: This manual describes what sipwise-asterisk is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sipwise-asterisk/sipwise-asterisk.sgml.gz

Format: postscript
Files: /usr/share/doc/sipwise-asterisk/sipwise-asterisk.ps.gz

Format: text
Files: /usr/share/doc/sipwise-asterisk/sipwise-asterisk.text.gz

Format: HTML
Index: /usr/share/doc/sipwise-asterisk/html/index.html
Files: /usr/share/doc/sipwise-asterisk/html/*.html


